### PR TITLE
fix(shared): remove the `keydown` listener once the `thyEnter` is destroyed

### PR DESCRIPTION
**Pull request by arturovt**

### CODE REVIEW

**Comment by why520crazy** [comment]
The reason why the keydown event was not unsubscribed is that the bound element is not a global, when the element is destroyed, the event will never be executed.

Are there any scenes that must be destroyed？

**Comment by why520crazy** [comment]
Including many other PR submitted by you, it is similar, as long as the event is not global, it seems unnecessary to remove it when it was destroyed.

**Comment by arturovt** [comment]
Hey @why520crazy . I'm not sure I understand what means "event is global". The rule of thumb is **always remove event listeners**.

Lemme show you the following scenario:
1) given this template `<button thyEnter></button>`
2) the `thyEnter` adds a `keydown` event listener
3) zone.js stores the `ZoneTask` within the `document.querySelector('button').__zone_symbol__keydownfalse` with the callback (which is `ThyEnterDirective.prototype.onKeydown`)
4) the `onKeydown` captures `this`
5) the `button` is removed from DOM
6) the Blink does re-layout (removes the button from the screen) and marks the `HTMLButtonElement` as _detached_ (to be GCed in the future)
7) the garbage collector never runs immediately, it then goes through the _detached_ DOM tree to remove objects that are not referenced (_dangling objects_)
8) the `button` element references the component through the `__zone_symbol__keydownfalse` and the component references the button through the `elementRef`
9) at the end we have a _circular reference_

I have a small article that explains that mechanism here: https://ng-guru.io/guide/garbage-collection/

Cheers 🙌

**Comment by why520crazy** [comment]
I see, thank you for your explanation.

**Review by why520crazy — APPROVED** [review]

**Comment by why520crazy** [comment]
@arturovt to verify whether there is a memory leak when do not remove event listener, I wrote an example：
https://stackblitz.com/edit/angular-ivy-eewmnf

create and destroy app-child component every 500ms, bind click event listener in app-child component, and create big data assignment to this.data, it is found that there is no memory leak through the performance tool of Chrome Browser.

image

If print data through the `console.log(this.data)` in the event, memory leaks do occur. 
do you know the specific reason or is there a vulnerability in this example？

**Comment by why520crazy** [comment]
I'm not very good at english. I hope you can understand, thanks！

**Comment by arturovt** [comment]
Hey @why520crazy 

To simplify the example I removed the `setInterval` from `constructor` and uncommented the button in `app.component.html`, so my template looks as follows:
```html
<button (click)="showChild = !showChild">Destroy</button>
<app-child *ngIf="showChild"></app-child>
```

Then I clicked the button and made snapshot:

Снимок экрана 2022-03-23 в 15 41 38

The `HTMLElement` is still retained and cannot be garbage collected. We see the address is `0x1ff2d24cd380`, it's an `HTMLElement` which is aggregated within the objects list, we can search it through objects:

Снимок экрана 2022-03-23 в 15 48 28

The `HTMLElement` is captures by `__zone_symbol__clickfalse` (which I showed you in the scenario).

**Comment by arturovt** [comment]
> Is this analysis display generated by your own tool?

I use Firefox heap analyzer and some addons written in Rust by Mozilla for querying snapshots.

I'm only curious what is the reason of **not** removing event listeners on destroy? Since this has been a best practice of not introducing memory leaks for decades starting from Angular 1.x (and other frameworks too):
> Listeners registered to scopes and elements are automatically cleaned up when they are destroyed, but if you registered a listener on a service, or registered a listener on a DOM node that isn't being deleted, you'll have to clean it up yourself or you risk introducing a memory leak. (https://docs.angularjs.org/guide/directive)

This is an example of the commit to Material where they remove event listeners that don't capture _this_: https://github.com/angular/components/commit/764030d04f0097fe8215ce96cc32610778bf3ace

Garbage collectors behave differently in all engines, but they use the same algorithm for determining if an object can be removed or not (reference counting). But we're not responsible for forcing GC for specific objects.

**Comment by why520crazy** [comment]
I have no oppose to removing event listeners on destroy, I admit that this is a best practice, I'm just exploring how to use it to cause memory leaks.

**Pull request merged**
