### PR TITLE
build: upgrade to Angular 13

### PR DESCRIPTION
**Pull request by arturovt**

### CODE REVIEW

**Comment by arturovt** [comment]
Hey @why520crazy . This is ready for review, **but not ready to merge**. The build and tests are passing, the CircleCI fails because of the `npm run report-coverage`.

Let me leave some notes for you:
- I've removed `china-division` package and just moved `.json` files locally that we depend on. The `china-division` package uses _sqlite3_, which requires to be compiled locally through `node-gyp`, and it fails to be compiled on my machine (I've got MacOS 12.3.1). I could guess that it compiles w/o issues for the core ngx-tethys team, but I'm guessing that other contributors could also face that issue.
- A lot of changes have been made by Angular migration schematics (it removed `entryComponents`).
- I've added comments for my code changes so reviewers can understand why that change has been made.

The only that's left is `report-coverage`. The reason why it's failing is because `lcov` file is empty (basically the code coverage is not generated). I don't really know why since I've never met that issue before.

We could discuss that issue here and I'm open to any ideas why it could fail.

**Comment by why520crazy** [comment]
I will take a look at this issue in the near future, thanks you very very very much!

**Comment by arturovt** [comment]
@why520crazy thanks for looking into it. Are you able to sync the `13.0.0-next` branch with the master? I see its `This branch is 247 commits behind master.`.

**Comment by why520crazy** [comment]
@arturovt  There was an old branch called `13.0.0-next`, I deleted it and create new branch `13.0.0-next` from master, so need you delete you local branch`13.0.0-next` and sync latest code, you can try it.

**Comment by why520crazy** [comment]
Sorry for my mistake, now the `13.0.0-next` branch is latest.

**Comment by why520crazy** [comment]
Hey @arturovt we are waiting for your PR merger before we can do the follow-up things, can you submit a new PR as soon as possible after fix unit test errors, thank you!

**Comment by arturovt** [comment]
Hey, yeah, I keep working on that. All tests were passing, but I just rebased the PR on master and started getting CDK drag&drop errors:
```
at toggleVisibility (:9876/_karma_webpack_/webpack:/node_modules/@angular/cdk/fesm2015/drag-drop.mjs:65:26)
at DragRef._cleanupDragArtifacts (:9876/_karma_webpack_/webpack:/node_modules/@angular/cdk/fesm2015/drag-drop.mjs:921:9)
```
The error is thrown asynchronously (when the `pointerup` event is dispatched) and I cannot track it down. I mean I cannot find the failing test.

Btw I also added the `sourceRoot` in angular.json, the coverage is generated now for cdk, but not for ngx-tethys 😞 Anyway, I believe we're on the right track.

**Comment by why520crazy** [comment]
The coverage of ngx-tethys is not generated because the unit test throw an error, sourceRoot is ok.

I  found that the test error was thyDragDrop in `shared/directives/thy-drag-drop.directive.ts`. we're looking at it.

**Comment by why520crazy** [comment]
I'll merge the code first and then fix the issue of thyDragDrop's unit test. Thanks!

**Comment by why520crazy** [comment]
image

**Pull request merged**
